# Generated by Django 4.2.14 on 2024-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='list',
            name='due_by',
            field=models.DateField(),
        ),
    ]
