# Generated by Django 4.2.14 on 2024-08-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_list_options_alter_list_due_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user_ID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='list_ID',
            new_name='list',
        ),
    ]
