# Generated by Django 4.2.14 on 2024-08-06 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_user_id_list_user_rename_list_id_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_by',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
